export POSTGRES_USER=meltano
export POSTGRES_PASSWORD=meltano
export POSTGRES_DB=meltano

export CLICKHOUSE_ADMIN_USER=meltano
export CLICKHOUSE_ADMIN_PASSWORD=meltano

export PARTNER_FAMILY_POSTGRES_ID=rc
export PARTNER_PLATFORM=rc-us

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export REDSHIFT_PASSWORD=
export REDSHIFT_USER=
export REDSHIFT_HOST=
export REDSHIFT_CLUSTER=
export REDSHIFT_PORT=5432
export REDSHIFT_URL=postgresql://${REDSHIFT_USER}:${REDSHIFT_PASSWORD}@${REDSHIFT_HOST}:${REDSHIFT_PORT}
export REDSHIFT_DEFAULT_DATABASE=dev
export DEV_SCHEMA_PREFIX=