services:
  postgres:
    build: .
    container_name: log_based_postgres
    environment:
      POSTGRES_USER: meltano
      POSTGRES_PASSWORD: meltano
      POSTGRES_DB: meltano
    ports:
      - "5433:5432"
    volumes:
      - ./custom-postgresql.conf:/docker-entrypoint-initdb.d/custom-postgresql.conf
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  
  clickhouse:
    image: bitnami/clickhouse:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_ADMIN_USER: meltano
      CLICKHOUSE_ADMIN_PASSWORD: meltano